//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AcademicMem
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AcademicMem()
    {
        this.Comments = new HashSet<Comment>();
        this.Rates = new HashSet<Rate>();
    }

    public int ID { get; set; }
    public byte[] Picture { get; set; }
    public string Faculty { get; set; }
    public string Department { get; set; }
    public double LectureAverage { get; set; }
    public double Average { get; set; }
    public Nullable<int> Rateg { get; set; }
    public Nullable<int> Rateb { get; set; }
    public string Comment { get; set; }
    public string Unvan { get; set; }
    public string Info { get; set; }
    public string Name_Surname { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Comment> Comments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Rate> Rates { get; set; }
}

public partial class Comment
{
    public Nullable<int> StudentID { get; set; }
    public Nullable<int> ID { get; set; }
    public string CommentID { get; set; }

    public virtual AcademicMem AcademicMem { get; set; }
    public virtual Student1 Student1 { get; set; }
}

public partial class CommentSection
{
    public string Username { get; set; }
    public string Subject { get; set; }
    public string Comment { get; set; }
    public int ID { get; set; }
    public string AcademicMemID { get; set; }
}

public partial class Faculty
{
    public int FacultyID { get; set; }
    public string FacultyName { get; set; }
    public string Department { get; set; }
    public string Lectures { get; set; }
}

public partial class Rate
{
    public Nullable<bool> RateG { get; set; }
    public Nullable<bool> RateB { get; set; }
    public Nullable<int> AcademicMemID { get; set; }
    public Nullable<int> StudentID { get; set; }
    public int RateID { get; set; }

    public virtual AcademicMem AcademicMem { get; set; }
    public virtual Student1 Student1 { get; set; }
}

public partial class Student1
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Student1()
    {
        this.Comments = new HashSet<Comment>();
        this.Rates = new HashSet<Rate>();
    }

    public int StudentID { get; set; }
    public string SName { get; set; }
    public string SSurname { get; set; }
    public string Email { get; set; }
    public string Department { get; set; }
    public byte[] Picture { get; set; }
    public string Faculty { get; set; }
    public string YearStarted { get; set; }
    public Nullable<double> GPA { get; set; }
    public string Password { get; set; }
    public Nullable<bool> IsOnline { get; set; }
    public Nullable<bool> IsGuest { get; set; }
    public Nullable<bool> IsAdmin { get; set; }
    public string Comment { get; set; }
    public string IncasePassword { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Comment> Comments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Rate> Rates { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
